create extension if not exists "pgcrypto";

create type public.product_status as enum ('active', 'archived');
create type public.order_status as enum (
  'pending',
  'processing',
  'shipped',
  'delivered',
  'canceled'
);
create type public.payment_status as enum (
  'unpaid',
  'pending',
  'paid',
  'failed',
  'refunded'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null unique,
  display_name text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (username ~ '^[a-z0-9_]{3,32}$')
);

create table public.products (
  id integer generated by default as identity primary key,
  name text not null,
  description text not null,
  price integer not null check (price >= 0),
  image_url text not null,
  inventory integer not null default 0 check (inventory >= 0),
  status public.product_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id integer not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status public.order_status not null default 'pending',
  subtotal integer not null check (subtotal >= 0),
  shipping_total integer not null default 0 check (shipping_total >= 0),
  tax_total integer not null default 0 check (tax_total >= 0),
  total integer not null check (total >= 0),
  currency text not null default 'USD',
  payment_status public.payment_status not null default 'unpaid',
  shipping_address jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id integer references public.products(id) on delete set null,
  product_name text not null,
  product_image_url text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total integer not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table public.order_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  event_type text not null,
  message text,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.normalize_username(raw_username text)
returns text
language sql
immutable
as $$
  select left(
    regexp_replace(lower(coalesce(raw_username, 'runner')), '[^a-z0-9_]', '', 'g'),
    32
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base_username text;
  final_username text;
  suffix text;
begin
  base_username := public.normalize_username(
    coalesce(
      new.raw_user_meta_data->>'username',
      split_part(new.email, '@', 1),
      'runner'
    )
  );

  if length(base_username) < 3 then
    base_username := base_username || 'run';
  end if;

  final_username := left(base_username, 32);

  while exists(select 1 from public.profiles where username = final_username) loop
    suffix := '_' || substr(gen_random_uuid()::text, 1, 6);
    final_username := left(base_username, 32 - length(suffix)) || suffix;
  end loop;

  insert into public.profiles (
    id,
    email,
    username,
    display_name,
    avatar_url
  )
  values (
    new.id,
    coalesce(new.email, ''),
    final_username,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name'),
    new.raw_user_meta_data->>'avatar_url'
  );

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.get_email_for_username(lookup_username text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select email
  from public.profiles
  where username = public.normalize_username(lookup_username)
  limit 1;
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.favorites enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_events enable row level security;

create policy "profiles are readable by owner"
on public.profiles for select
using (auth.uid() = id);

create policy "profiles are insertable by owner"
on public.profiles for insert
with check (auth.uid() = id);

create policy "profiles are updatable by owner"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "active products are public"
on public.products for select
using (status = 'active');

create policy "favorites are readable by owner"
on public.favorites for select
using (auth.uid() = user_id);

create policy "favorites are insertable by owner"
on public.favorites for insert
with check (auth.uid() = user_id);

create policy "favorites are deletable by owner"
on public.favorites for delete
using (auth.uid() = user_id);

create policy "orders are readable by owner"
on public.orders for select
using (auth.uid() = user_id);

create policy "orders are insertable by owner"
on public.orders for insert
with check (auth.uid() = user_id);

create policy "pending orders are cancelable by owner"
on public.orders for update
using (auth.uid() = user_id and status in ('pending', 'processing'))
with check (auth.uid() = user_id and status = 'canceled');

create policy "order items are readable by order owner"
on public.order_items for select
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

create policy "order items are insertable by order owner"
on public.order_items for insert
with check (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

create policy "order events are readable by order owner"
on public.order_events for select
using (
  exists (
    select 1 from public.orders
    where orders.id = order_events.order_id
      and orders.user_id = auth.uid()
  )
);

create policy "order events are insertable by order owner"
on public.order_events for insert
with check (
  exists (
    select 1 from public.orders
    where orders.id = order_events.order_id
      and orders.user_id = auth.uid()
  )
);

insert into public.products (
  id,
  name,
  description,
  price,
  image_url,
  inventory,
  status
)
values
  (1, 'Aero Sprint X', 'Featherweight tempo shoe for fast road sessions.', 129, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80', 24, 'active'),
  (2, 'Trail Ember Pro', 'Aggressive grip and rock protection for technical trails.', 154, 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=900&q=80', 18, 'active'),
  (3, 'Cloud Mile 3', 'Soft daily trainer built for high-mileage comfort.', 118, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=900&q=80', 32, 'active'),
  (4, 'Marathon Carbon', 'Carbon plate propulsion for race-day efficiency.', 219, 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80', 12, 'active'),
  (5, 'City Run Knit', 'Breathable knit upper for relaxed urban runs.', 96, 'https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=900&q=80', 29, 'active'),
  (6, 'Stability Core', 'Guided support for smooth, confident daily training.', 142, 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80', 21, 'active'),
  (7, 'Recovery Glide', 'Plush foam and wide base for easy recovery miles.', 109, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80', 17, 'active'),
  (8, 'Track Volt Elite', 'Snappy low-profile racer for intervals and track work.', 168, 'https://images.unsplash.com/photo-1605408499391-6368c628ef42?auto=format&fit=crop&w=900&q=80', 15, 'active')
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image_url = excluded.image_url,
  inventory = excluded.inventory,
  status = excluded.status;

select setval(pg_get_serial_sequence('public.products', 'id'), 8, true);
